baseURL = "https://vixviz.com/"
languageCode = "en-us"
title = "VIXVIZ"
theme = "ananke"
[params]
  slogan = "Visualize VIX, Master Volatility“

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
